#pragma checksum "ModelType.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "3d652ce8ac7900db739805ac73868e62da8ba977"
// <auto-generated/>
#pragma warning disable 1591
[assembly:global::RazorLight.Razor.RazorLightTemplateAttribute(@"ModelType.cshtml", typeof(Test.ModelType))]
namespace Test
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    public class ModelType : RazorLight.TemplatePage<object>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("<p>");
#nullable restore
#line 2 "ModelType.cshtml"
Write(Model.GetType());

#line default
#line hidden
#nullable disable
            WriteLiteral("</p>");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
